# Generated by Django 5.1.5 on 2025-02-06 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Memembership",
            new_name="Membership",
        ),
    ]
