# Generated by Django 5.1.5 on 2025-02-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="tags",
            field=models.ManyToManyField(blank=True, to="rooms.tag"),
        ),
    ]
